# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Vincentqyw"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "quant": 
        filters: ["quant", "quantitative", "factor", "Financial", "q-fin", "factor analysis", "Fintech", "Value",
"Momentum",
"Quality",
"Machine Learning",
"Algo Trading",
"Statistical Arbitrage",
"Pairs Trading",
"Risk Metrics",
"Optimization",
"High Frequency",
"Infrastructure",
"Alternative Data",
"Data Mining",
"ETF",
"Factor Construction",
"Order Book",
"Market Structure",
"Market Regimes",
"Timing",
"Deep Learning",
"Price Prediction",
"Transaction Cost",
"Analysis",
"Decomposition",
"Attribution",
"Trading Algorithms",
"Execution",
"Environmental",
"Social",
"Governance",
"Factor Models",
"Correlation",
"Reinforcement Learning",
"Portfolio",
"Electronic Markets",
"Liquidity",
"Crowding",
"Capacity",
"Natural Language",
"Sentiment",
"Volatility",
"Risk Premia",
"Cointegration",
"Mean Reversion",
"Delta Neutral",
"Market Making",
"Portfolio Construction",
"Factors",
"Execution Cost",
"Slippage",
"Forecasting",
"Prediction",
"Systematic",
"Bonds",
"Emerging Markets",
"Pattern Recognition",
"Signal Generation",
"Day Trading",
"Portfolio Allocation",
"Risk",
"Market States",
"Detection",
"Macro",
"Quantum Computing",
"Cross-Section",
"Options",
"Volatility Surface",
"Model Risk",
"Framework",
"Testing",
"Cryptocurrency",
"Alternative Beta",
"Events",
"Rebalancing",
"Commodities",
"Model Validation",
"Performance",
"Currency Trading",
"Real-Time Systems",
"Options Trading"]
    "低延迟交易":
        filters: [
"RDMA",
"Kernel Bypass",
"TCP Offload",
"XDP",
"DPDK",
"Solarflare Onload",
"PCIe DMA",
"Shared Memory IPC",
"Zero Copy",
"Memory Mapping",
"CPU Affinity",
"NUMA Optimization",
"Cache Alignment",
"Lock-Free Programming",
"Real-Time Priority",
"Interrupt Steering",
"NIC RSS",
"TOE",
"UDP Multicast",
"PTP Timing",
"Hardware Timestamping",
"FPGA Acceleration",
"ASIC Implementation",
"SmartNIC",
"InfiniBand",
"RoCE",
"iWARP",
"Memory Fence",
"Busy Polling",
"Event Loop",
"Kernel Tuning",
"IRQ Balance",
"Core Isolation",
"Hugepages",
"Memory Prefetch",
"Branch Prediction",
"Inline Assembly",
"SIMD Instructions",
"Cache Prefetching",
"Thread Pinning",
"DMA Engine",
"Direct Cache Access",
"TCP Fast Open",
"Market Data Handlers",
"Order Entry Path",
"Latency Monitoring",
"Jitter Control",
"Network Tapping",
"Time Synchronization",
"Colocation Services"
]

